# Generated by Django 3.1.1 on 2020-11-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderline',
            table=None,
        ),
    ]
